### ISSUE TITLE
記事の中に誤字と思われる文章がある

### ISSUE THREAD

**Issue by Omuretsu** [Hiratake/hiratake-web#1320]
https://github.com/Hiratake/hiratake-web/blob/c20ad2951debb87c311eb9d4ebbf3464776706db/content/blog/2024/08/05.md?plain=1#L25

`年商1,000億円`と思われる文章が、`年商1,000奥円`になっています。

**Comment by Hiratake** [comment]
@Omuretsu 
ありがとうございます！修正しました✅️
