### ISSUE TITLE
タブレットサイズのときにトップページの「もっとみる」が右に張り付く

### ISSUE THREAD

**Issue by book000** [Hiratake/hiratake-web#1433]
ウィンドウがタブレットサイズ（768px～1200px）のときに、トップページの「もっとみる」ボタンの右側マージンが抜けている気がします。
ちょっと違和感感じて起票しますが、意図的ならクローズください。

## ～768px

![image](https://github.com/user-attachments/assets/72a6a528-c638-46f5-88a9-f0c4727128d8)

## 768px ～ 1200px

![image](https://github.com/user-attachments/assets/dfd39b08-5cdd-471f-96bb-638bf4cc812f)

## 1200px～

![image](https://github.com/user-attachments/assets/0550c30d-e970-41f2-bb16-847f38e7316c)

環境は以下のとおりです。

- Windows 23H2 (Build 22631.4317)
- Firefox stable 131.0.3

**Comment by Hiratake** [comment]
`box-content` がいらない子かも
