### ISSUE TITLE
PCの構成や使用している周辺機器についての記事が読みたい

### ISSUE THREAD

**Issue by Omuretsu** [Hiratake/hiratake-web#430]

**Comment by Hiratake** [comment]
まじで書くことがなにもない。
なにか他に書いてほしいことありますか？私はこれ以上書くことがありません…。
写真は一切載せる気ないです。

- #444

特になければ火曜くらいに公開しようと思ってます。

**Comment by Hiratake** [comment]
プレビュー
https://5db295ef.hiratake.pages.dev/blog/20230711
