### ISSUE TITLE
小学校時代の独自通貨についての記事が読みたい

### ISSUE THREAD

**Issue by Omuretsu** [Hiratake/hiratake-web#543]
https://github.com/Hiratake/hiratake-web/blob/3ffe12fb9b806ffb9d091f0960deed484631ed1e/content/blog/20230727.md?plain=1#L15C6-L15C6

気になりました。

**Comment by Hiratake** [comment]
そういうものがあった、ということしか覚えていません。なので、かけません。書けないのでこちらはクローズします。

**Comment by Omuretsu** [comment]
🥲
