### ISSUE TITLE
「GitHubで編集を提案」のリンク先が `git+https` となっている

### ISSUE THREAD

**Issue by book000** [Hiratake/hiratake-web#59]
![](https://i.imgur.com/7ony3py.png)

https://github.com/Hiratake/hiratake-web/blob/82114b88b0d3232c90eb2ede60d49e83e04df07e/pages/_slug.vue#L180-L183

`const repo = this.$config.packageRepository.replace(/\.git$/, '').replace(/^git+/, '')` ?

**Comment by Hiratake** [comment]
ローカルだと `git+` なんて付かないから謎だ
無理にpackage.jsonのrepositoryからとってこなくてもいい気がしてきた
