### ISSUE TITLE
RSSフィードの本文に含まれるコードブロックがおかしい

### ISSUE THREAD

**Issue by Hiratake** [Hiratake/hiratake-web#691]
RSSフィードで配信している内容の、本文に含まれるコードブロックが正しく表示されない。

**Comment by book000** [comment]
- 改行が消える
- `<` `>` の前後にスペースが入る？

![IMG_3280](https://github.com/Hiratake/hiratake-web/assets/8929706/8b7a3105-35e9-41b0-b655-ded7591bdef8)

**Comment by Hiratake** [comment]
コードブロックを処理する方法が思いつかなさ過ぎる

**Comment by Hiratake** [comment]
https://togithub.com/nuxt/content/issues/2306

**Comment by Hiratake** [comment]
処理してるのはここ
https://github.com/Hiratake/hiratake-web/blob/main/src/server/utils/content.ts#L11

コードブロックとそれ以外で処理分けないと厳しそうかも？

**Comment by Hiratake** [comment]
@book000 
とりあえず調整してみたので様子見。おかしかったら教えて下さい🙏

- #1115
