### ISSUE TITLE
RSSフィードを購読していると、Webサイトがデプロイされるごとにすべての記事が未読扱いになる

### ISSUE THREAD

**Issue by book000** [Hiratake/hiratake-web#854]
`https://hiratake.xyz/feed.xml` を購読していると、タイトルの問題が発生します。

feed.xml を読んだところ、記事のURLのドメインが `9365be00.hiratake.pages.dev` になっており、これがデプロイごとに更新されるために発生しているものと推測されます。

下記の箇所に問題がありそうです:
https://github.com/Hiratake/hiratake-web/blob/c36941ddde1f65d63bc90df374d3761c2ce4cf62/web/src/server/routes/feed.xml.ts#L9

なお、以下のプルリクエストの修正漏れと思われます。
https://github.com/Hiratake/hiratake-web/pull/836

**Comment by Hiratake** [comment]
https://developers.cloudflare.com/pages/platform/build-configuration/#environment-variables
`CF_PAGES_URL` はオーバーライドできるらしいので、本番環境に設定を入れてデプロイしなおしました。
たぶん修正されると思います🙏
直っていないようなら再オープンしていただけると🫵
